
project_id = "glhcnrujqettwvrdvjkx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions.respond-to-application]
verify_jwt = false

[functions.notify-applicant]
verify_jwt = false

[functions.project-chat-init]
verify_jwt = false
