// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glhcnrujqettwvrdvjkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsaGNucnVqcWV0dHd2cmR2amt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTE3MTAsImV4cCI6MjA2MDE4NzcxMH0.dIstRaWxZreXkGjfF6fi13eX21MqkoMfHi9rXS948_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);